import type { CourseModule, Lesson } from './types';

/* ─────────────────────────────────────────────────────────────────────────────
   MODULES
───────────────────────────────────────────────────────────────────────────── */

export const MODULES: CourseModule[] = [
  {
    id: 'primeros-pasos',
    title: 'Primeros pasos',
    description: 'Las bases del neerlandés: saludos, números, colores y vocabulario esencial para empezar a comunicarte.',
    order: 1,
    emoji: '🌱',
    level: 'A0',
    color: '#1D0084',
  },
  {
    id: 'vida-cotidiana',
    title: 'La vida cotidiana',
    description: 'Vocabulario y expresiones para el día a día: la casa, las compras y el tiempo libre.',
    order: 2,
    emoji: '🏡',
    level: 'A1',
    color: '#025dc7',
  },
];

/* ─────────────────────────────────────────────────────────────────────────────
   MODULE 1 — PRIMEROS PASOS
───────────────────────────────────────────────────────────────────────────── */

const lesson_saludos: Lesson = {
  id: 'saludos-y-presentaciones',
  moduleId: 'primeros-pasos',
  title: 'Saludos y presentaciones',
  subtitle: 'Cómo saludar y presentarte en neerlandés',
  order: 1,
  learningObjective: 'Saludar formal e informalmente y presentarte con tu nombre',
  estimatedMinutes: 15,
  blocks: [
    {
      type: 'vocabulary',
      items: [
        {
          id: 'hallo',
          dutch: 'hallo',
          spanish: 'hola',
          article: null,
          emoji: '👋',
          color: '#1D0084',
          exampleNl: 'Hallo, hoe gaat het?',
          exampleEs: '¡Hola, cómo estás?',
          category: 'saludos',
          difficulty: 'A0',
        },
        {
          id: 'goedemorgen',
          dutch: 'goedemorgen',
          spanish: 'buenos días',
          article: null,
          emoji: '🌅',
          color: '#025dc7',
          exampleNl: 'Goedemorgen! Hoe slep je?',
          exampleEs: '¡Buenos días! ¿Cómo dormiste?',
          category: 'saludos',
          difficulty: 'A0',
        },
        {
          id: 'goedemiddag',
          dutch: 'goedemiddag',
          spanish: 'buenas tardes',
          article: null,
          emoji: '☀️',
          color: '#0b4db5',
          exampleNl: 'Goedemiddag, meneer!',
          exampleEs: '¡Buenas tardes, señor!',
          category: 'saludos',
          difficulty: 'A0',
        },
        {
          id: 'tot-ziens',
          dutch: 'tot ziens',
          spanish: 'hasta luego',
          article: null,
          emoji: '👋',
          color: '#0a3d9e',
          exampleNl: 'Tot ziens! Tot morgen.',
          exampleEs: '¡Hasta luego! Hasta mañana.',
          category: 'saludos',
          difficulty: 'A0',
        },
        {
          id: 'bedankt',
          dutch: 'bedankt',
          spanish: 'gracias',
          article: null,
          emoji: '🙏',
          color: '#1440a0',
          exampleNl: 'Bedankt voor je hulp!',
          exampleEs: '¡Gracias por tu ayuda!',
          category: 'saludos',
          difficulty: 'A0',
        },
        {
          id: 'alsjeblieft',
          dutch: 'alsjeblieft',
          spanish: 'por favor',
          article: null,
          emoji: '🤲',
          color: '#0d5295',
          exampleNl: 'Een koffie, alsjeblieft.',
          exampleEs: 'Un café, por favor.',
          category: 'saludos',
          difficulty: 'A0',
        },
      ],
    },
    {
      type: 'phrases',
      items: [
        {
          id: 'phrase-hoe-heet-je',
          dutch: 'Hoe heet je?',
          spanish: '¿Cómo te llamas?',
          context: 'Preguntando el nombre',
        },
        {
          id: 'phrase-ik-heet',
          dutch: 'Ik heet...',
          spanish: 'Me llamo...',
          context: 'Presentándote',
        },
        {
          id: 'phrase-hoe-gaat-het',
          dutch: 'Hoe gaat het?',
          spanish: '¿Cómo estás?',
          context: 'Saludando informalmente',
        },
        {
          id: 'phrase-goed-dank-je',
          dutch: 'Goed, dank je. En jij?',
          spanish: 'Bien, gracias. ¿Y tú?',
          context: 'Respondiendo al saludo',
        },
      ],
    },
    {
      type: 'practice',
      exercises: [
        {
          id: 'ex-bedankt-mc',
          type: 'multiple_choice',
          prompt: '¿Cómo se dice "gracias" en neerlandés?',
          options: ['bedankt', 'hallo', 'tot ziens', 'goedemorgen'],
          correctAnswer: 'bedankt',
          explanation: 'Bedankt es la forma más común de decir gracias.',
        },
        {
          id: 'ex-goedemorgen-mc',
          type: 'multiple_choice',
          prompt: '¿Qué significa "goedemorgen"?',
          options: ['buenos días', 'buenas tardes', 'hasta luego', 'por favor'],
          correctAnswer: 'buenos días',
        },
        {
          id: 'ex-hoe-heet-mc',
          type: 'multiple_choice',
          prompt: '¿Qué frase usas para preguntarle el nombre a alguien?',
          options: ['Hoe heet je?', 'Hoe gaat het?', 'Tot ziens!', 'Bedankt!'],
          correctAnswer: 'Hoe heet je?',
        },
        {
          id: 'ex-alsjeblieft-write',
          type: 'write_answer',
          prompt: '¿Cómo se dice "por favor" en neerlandés?',
          correctAnswer: 'alsjeblieft',
          hint: 'Empieza con "als..."',
        },
      ],
    },
    {
      type: 'dialogue',
      dialogue: {
        id: 'dialogue-primer-encuentro',
        title: 'Primer encuentro',
        context: 'Anna y Tom se conocen en clase por primera vez.',
        lines: [
          {
            id: 'line-1',
            speaker: 'Anna',
            dutch: 'Hallo! Ik heet Anna. Hoe heet jij?',
            spanish: '¡Hola! Me llamo Anna. ¿Cómo te llamas tú?',
          },
          {
            id: 'line-2',
            speaker: 'Tom',
            dutch: 'Hallo Anna! Ik heet Tom. Aangenaam!',
            spanish: '¡Hola Anna! Me llamo Tom. ¡Encantado!',
          },
          {
            id: 'line-3',
            speaker: 'Anna',
            dutch: 'Hoe gaat het, Tom?',
            spanish: '¿Cómo estás, Tom?',
          },
          {
            id: 'line-4',
            speaker: 'Tom',
            dutch: 'Goed, bedankt! En jij?',
            spanish: '¡Bien, gracias! ¿Y tú?',
          },
          {
            id: 'line-5',
            speaker: 'Anna',
            dutch: 'Ook goed, dank je. Tot ziens!',
            spanish: 'También bien, gracias. ¡Hasta luego!',
          },
        ],
      },
    },
    { type: 'review' },
  ],
};

const lesson_numeros: Lesson = {
  id: 'numeros-y-colores',
  moduleId: 'primeros-pasos',
  title: 'Números y colores',
  subtitle: 'Cuenta hasta 10 y nombra los colores básicos',
  order: 2,
  learningObjective: 'Contar del 1 al 10 y reconocer los colores principales',
  estimatedMinutes: 20,
  blocks: [
    {
      type: 'vocabulary',
      items: [
        {
          id: 'een',
          dutch: 'één',
          spanish: 'uno',
          article: null,
          emoji: '1️⃣',
          color: '#1D0084',
          exampleNl: 'Ik heb één broer.',
          exampleEs: 'Tengo un hermano.',
          category: 'números',
          difficulty: 'A0',
        },
        {
          id: 'twee',
          dutch: 'twee',
          spanish: 'dos',
          article: null,
          emoji: '2️⃣',
          color: '#025dc7',
          exampleNl: 'Twee appels, alsjeblieft.',
          exampleEs: 'Dos manzanas, por favor.',
          category: 'números',
          difficulty: 'A0',
        },
        {
          id: 'drie',
          dutch: 'drie',
          spanish: 'tres',
          article: null,
          emoji: '3️⃣',
          color: '#0b4db5',
          exampleNl: 'Er zijn drie katten.',
          exampleEs: 'Hay tres gatos.',
          category: 'números',
          difficulty: 'A0',
        },
        {
          id: 'vier',
          dutch: 'vier',
          spanish: 'cuatro',
          article: null,
          emoji: '4️⃣',
          color: '#0a3d9e',
          exampleNl: 'Ik werk vier dagen.',
          exampleEs: 'Trabajo cuatro días.',
          category: 'números',
          difficulty: 'A0',
        },
        {
          id: 'vijf',
          dutch: 'vijf',
          spanish: 'cinco',
          article: null,
          emoji: '5️⃣',
          color: '#1440a0',
          exampleNl: 'Het zijn vijf minuten lopen.',
          exampleEs: 'Son cinco minutos a pie.',
          category: 'números',
          difficulty: 'A0',
        },
        {
          id: 'rood',
          dutch: 'rood',
          spanish: 'rojo',
          article: null,
          emoji: '🔴',
          color: '#0d5295',
          exampleNl: 'De auto is rood.',
          exampleEs: 'El coche es rojo.',
          category: 'colores',
          difficulty: 'A0',
        },
        {
          id: 'blauw',
          dutch: 'blauw',
          spanish: 'azul',
          article: null,
          emoji: '🔵',
          color: '#025dc7',
          exampleNl: 'De lucht is blauw.',
          exampleEs: 'El cielo es azul.',
          category: 'colores',
          difficulty: 'A0',
        },
        {
          id: 'groen',
          dutch: 'groen',
          spanish: 'verde',
          article: null,
          emoji: '🟢',
          color: '#1D0084',
          exampleNl: 'Het gras is groen.',
          exampleEs: 'La hierba es verde.',
          category: 'colores',
          difficulty: 'A0',
        },
      ],
    },
    {
      type: 'phrases',
      items: [
        {
          id: 'phrase-hoeveel',
          dutch: 'Hoeveel?',
          spanish: '¿Cuántos?',
          context: 'Preguntando cantidad',
        },
        {
          id: 'phrase-dat-zijn',
          dutch: 'Dat zijn... stuks.',
          spanish: 'Son... unidades.',
          context: 'Indicando cantidad',
        },
        {
          id: 'phrase-welke-kleur',
          dutch: 'Welke kleur is dat?',
          spanish: '¿Qué color es ese?',
          context: 'Preguntando por un color',
        },
        {
          id: 'phrase-favoriete-kleur',
          dutch: 'Mijn favoriete kleur is blauw.',
          spanish: 'Mi color favorito es el azul.',
          context: 'Expresando preferencias',
        },
      ],
    },
    {
      type: 'practice',
      exercises: [
        {
          id: 'ex-vier-mc',
          type: 'multiple_choice',
          prompt: '¿Cuánto es "vier"?',
          options: ['3', '4', '5', '6'],
          correctAnswer: '4',
        },
        {
          id: 'ex-rood-mc',
          type: 'multiple_choice',
          prompt: '¿Cómo se dice "rojo" en neerlandés?',
          options: ['rood', 'blauw', 'groen', 'geel'],
          correctAnswer: 'rood',
        },
        {
          id: 'ex-welke-kleur-order',
          type: 'order_sentence',
          prompt: 'Ordena: "kleur / Welke / dat? / is"',
          options: ['Welke', 'kleur', 'is', 'dat?'],
          correctAnswer: 'Welke kleur is dat?',
        },
        {
          id: 'ex-groen-write',
          type: 'write_answer',
          prompt: '¿Cómo se dice "verde" en neerlandés?',
          correctAnswer: 'groen',
        },
      ],
    },
    {
      type: 'dialogue',
      dialogue: {
        id: 'dialogue-tienda',
        title: 'En la tienda',
        context: 'Una cliente pregunta por colores disponibles en una tienda.',
        lines: [
          {
            id: 'line-1',
            speaker: 'Cliente',
            dutch: 'Goedemiddag! Heeft u dit in blauw?',
            spanish: '¡Buenas tardes! ¿Tienen esto en azul?',
          },
          {
            id: 'line-2',
            speaker: 'Verkoper',
            dutch: 'Ja, we hebben blauw, rood en groen.',
            spanish: 'Sí, tenemos azul, rojo y verde.',
          },
          {
            id: 'line-3',
            speaker: 'Cliente',
            dutch: 'Hoeveel stuks zijn er in blauw?',
            spanish: '¿Cuántas unidades hay en azul?',
          },
          {
            id: 'line-4',
            speaker: 'Verkoper',
            dutch: 'Er zijn vijf stuks in blauw.',
            spanish: 'Hay cinco unidades en azul.',
          },
          {
            id: 'line-5',
            speaker: 'Cliente',
            dutch: 'Mooi! Ik neem twee, alsjeblieft.',
            spanish: '¡Perfecto! Me llevo dos, por favor.',
          },
        ],
      },
    },
    { type: 'review' },
  ],
};

const lesson_ciudad: Lesson = {
  id: 'en-la-ciudad',
  moduleId: 'primeros-pasos',
  title: 'En la ciudad',
  subtitle: 'Vocabulario esencial para moverte por una ciudad neerlandesa',
  order: 3,
  learningObjective: 'Reconocer lugares clave en la ciudad y pedir indicaciones básicas',
  estimatedMinutes: 20,
  blocks: [
    {
      type: 'vocabulary',
      items: [
        {
          id: 'straat',
          dutch: 'straat',
          spanish: 'la calle',
          article: 'de',
          emoji: '🛣️',
          color: '#1D0084',
          exampleNl: 'De straat is erg druk.',
          exampleEs: 'La calle está muy concurrida.',
          category: 'ciudad',
          difficulty: 'A0',
        },
        {
          id: 'winkel',
          dutch: 'winkel',
          spanish: 'la tienda',
          article: 'de',
          emoji: '🏪',
          color: '#025dc7',
          exampleNl: 'De winkel is om de hoek.',
          exampleEs: 'La tienda está a la vuelta de la esquina.',
          category: 'ciudad',
          difficulty: 'A0',
        },
        {
          id: 'trein',
          dutch: 'trein',
          spanish: 'el tren',
          article: 'de',
          emoji: '🚆',
          color: '#0b4db5',
          exampleNl: 'De trein vertrekt om negen uur.',
          exampleEs: 'El tren sale a las nueve.',
          category: 'ciudad',
          difficulty: 'A0',
        },
        {
          id: 'park',
          dutch: 'park',
          spanish: 'el parque',
          article: 'het',
          emoji: '🌳',
          color: '#0a3d9e',
          exampleNl: 'Het park is heel mooi in de lente.',
          exampleEs: 'El parque es muy bonito en primavera.',
          category: 'ciudad',
          difficulty: 'A0',
        },
        {
          id: 'bus',
          dutch: 'bus',
          spanish: 'el autobús',
          article: 'de',
          emoji: '🚌',
          color: '#1440a0',
          exampleNl: 'De bus komt over vijf minuten.',
          exampleEs: 'El autobús llega en cinco minutos.',
          category: 'ciudad',
          difficulty: 'A0',
        },
        {
          id: 'markt',
          dutch: 'markt',
          spanish: 'el mercado',
          article: 'de',
          emoji: '🛍️',
          color: '#0d5295',
          exampleNl: 'Op de markt koop ik verse groenten.',
          exampleEs: 'En el mercado compro verduras frescas.',
          category: 'ciudad',
          difficulty: 'A0',
        },
      ],
    },
    {
      type: 'phrases',
      items: [
        {
          id: 'phrase-waar-station',
          dutch: 'Waar is het station?',
          spanish: '¿Dónde está la estación?',
          context: 'Pidiendo indicaciones',
        },
        {
          id: 'phrase-hoe-kom-ik',
          dutch: 'Hoe kom ik naar...?',
          spanish: '¿Cómo llego a...?',
          context: 'Preguntando la ruta',
        },
        {
          id: 'phrase-rechtsaf-links',
          dutch: 'Rechtsaf, dan links.',
          spanish: 'A la derecha, luego a la izquierda.',
          context: 'Dando indicaciones',
        },
        {
          id: 'phrase-vlakbij',
          dutch: 'Het is vlakbij.',
          spanish: 'Está muy cerca.',
          context: 'Indicando distancia',
        },
      ],
    },
    {
      type: 'practice',
      exercises: [
        {
          id: 'ex-trein-artikel-mc',
          type: 'multiple_choice',
          prompt: '¿Qué artículo lleva "trein"?',
          options: ['de', 'het', 'een', 'geen'],
          correctAnswer: 'de',
        },
        {
          id: 'ex-markt-mc',
          type: 'multiple_choice',
          prompt: '¿Cómo se dice "el mercado" en neerlandés?',
          options: ['de markt', 'de winkel', 'het park', 'de straat'],
          correctAnswer: 'de markt',
        },
        {
          id: 'ex-indicaciones-mc',
          type: 'multiple_choice',
          prompt: '¿Qué frase usas para pedir indicaciones?',
          options: ['Waar is het station?', 'Hoe gaat het?', 'Bedankt!', 'Tot ziens!'],
          correctAnswer: 'Waar is het station?',
        },
        {
          id: 'ex-winkel-write',
          type: 'write_answer',
          prompt: '¿Cómo se dice "la tienda" en neerlandés? (con artículo)',
          correctAnswer: 'de winkel',
          hint: 'El artículo es "de"',
        },
      ],
    },
    {
      type: 'dialogue',
      dialogue: {
        id: 'dialogue-camino',
        title: 'Preguntando por el camino',
        context: 'Un turista le pide indicaciones a un local para llegar al mercado.',
        lines: [
          {
            id: 'line-1',
            speaker: 'Turista',
            dutch: 'Goedemorgen! Waar is de markt?',
            spanish: '¡Buenos días! ¿Dónde está el mercado?',
          },
          {
            id: 'line-2',
            speaker: 'Local',
            dutch: 'De markt is vlakbij. Ga rechtdoor en dan linksaf.',
            spanish: 'El mercado está muy cerca. Sigue recto y luego gira a la izquierda.',
          },
          {
            id: 'line-3',
            speaker: 'Turista',
            dutch: 'Is het ver lopen?',
            spanish: '¿Está lejos caminando?',
          },
          {
            id: 'line-4',
            speaker: 'Local',
            dutch: 'Nee, vijf minuten lopen.',
            spanish: 'No, cinco minutos a pie.',
          },
          {
            id: 'line-5',
            speaker: 'Turista',
            dutch: 'Hartelijk bedankt!',
            spanish: '¡Muchas gracias!',
          },
        ],
      },
    },
    { type: 'review' },
  ],
};

/* ─────────────────────────────────────────────────────────────────────────────
   MODULE 2 — VIDA COTIDIANA
───────────────────────────────────────────────────────────────────────────── */

const lesson_casa: Lesson = {
  id: 'en-casa',
  moduleId: 'vida-cotidiana',
  title: 'En casa',
  subtitle: 'Las habitaciones y objetos del hogar',
  order: 1,
  learningObjective: 'Describir tu casa y las acciones que realizas en ella',
  estimatedMinutes: 20,
  blocks: [
    {
      type: 'vocabulary',
      items: [
        {
          id: 'keuken',
          dutch: 'keuken',
          spanish: 'la cocina',
          article: 'de',
          emoji: '🍳',
          color: '#1D0084',
          exampleNl: 'Ik kook elke dag in de keuken.',
          exampleEs: 'Cocino todos los días en la cocina.',
          category: 'hogar',
          difficulty: 'A1',
        },
        {
          id: 'slaapkamer',
          dutch: 'slaapkamer',
          spanish: 'el dormitorio',
          article: 'de',
          emoji: '🛏️',
          color: '#025dc7',
          exampleNl: 'Mijn slaapkamer is groot en licht.',
          exampleEs: 'Mi dormitorio es grande y luminoso.',
          category: 'hogar',
          difficulty: 'A1',
        },
        {
          id: 'badkamer',
          dutch: 'badkamer',
          spanish: 'el cuarto de baño',
          article: 'de',
          emoji: '🚿',
          color: '#0b4db5',
          exampleNl: 'De badkamer is naast de slaapkamer.',
          exampleEs: 'El cuarto de baño está al lado del dormitorio.',
          category: 'hogar',
          difficulty: 'A1',
        },
        {
          id: 'woonkamer',
          dutch: 'woonkamer',
          spanish: 'el salón',
          article: 'de',
          emoji: '🛋️',
          color: '#0a3d9e',
          exampleNl: 'We kijken tv in de woonkamer.',
          exampleEs: 'Vemos la tele en el salón.',
          category: 'hogar',
          difficulty: 'A1',
        },
        {
          id: 'raam',
          dutch: 'raam',
          spanish: 'la ventana',
          article: 'het',
          emoji: '🪟',
          color: '#1440a0',
          exampleNl: 'Sluit het raam, het is koud.',
          exampleEs: 'Cierra la ventana, hace frío.',
          category: 'hogar',
          difficulty: 'A1',
        },
        {
          id: 'tafel',
          dutch: 'tafel',
          spanish: 'la mesa',
          article: 'de',
          emoji: '🪑',
          color: '#0d5295',
          exampleNl: 'We eten aan de tafel.',
          exampleEs: 'Comemos en la mesa.',
          category: 'hogar',
          difficulty: 'A1',
        },
      ],
    },
    {
      type: 'phrases',
      items: [
        {
          id: 'phrase-kook-keuken',
          dutch: 'Ik kook in de keuken.',
          spanish: 'Cocino en la cocina.',
          context: 'Describiendo actividades',
        },
        {
          id: 'phrase-slaapkamer-groot',
          dutch: 'Mijn slaapkamer is groot.',
          spanish: 'Mi dormitorio es grande.',
          context: 'Describiendo el hogar',
        },
        {
          id: 'phrase-sluit-raam',
          dutch: 'Sluit het raam, alsjeblieft.',
          spanish: 'Cierra la ventana, por favor.',
          context: 'Pidiendo algo en casa',
        },
        {
          id: 'phrase-waar-badkamer',
          dutch: 'Waar is de badkamer?',
          spanish: '¿Dónde está el cuarto de baño?',
          context: 'Preguntando en casa',
        },
      ],
    },
    {
      type: 'practice',
      exercises: [
        {
          id: 'ex-raam-artikel-mc',
          type: 'multiple_choice',
          prompt: '¿Qué artículo lleva "raam"?',
          options: ['het', 'de', 'een', 'geen'],
          correctAnswer: 'het',
        },
        {
          id: 'ex-salon-mc',
          type: 'multiple_choice',
          prompt: '¿Cómo se dice "el salón"?',
          options: ['woonkamer', 'slaapkamer', 'keuken', 'badkamer'],
          correctAnswer: 'woonkamer',
        },
        {
          id: 'ex-keuken-listen',
          type: 'listen_and_choose',
          prompt: 'Escucha y elige la habitación correcta: "Ik kook hier elke dag."',
          options: ['keuken', 'slaapkamer', 'badkamer', 'woonkamer'],
          correctAnswer: 'keuken',
          explanation: 'Se cocina en la cocina (keuken).',
        },
        {
          id: 'ex-badkamer-write',
          type: 'write_answer',
          prompt: '¿Cómo preguntas dónde está el cuarto de baño?',
          correctAnswer: 'Waar is de badkamer?',
        },
      ],
    },
    {
      type: 'dialogue',
      dialogue: {
        id: 'dialogue-casa',
        title: 'Mostrando la casa',
        context: 'Marta le muestra su nuevo piso a su amiga Lisa.',
        lines: [
          {
            id: 'line-1',
            speaker: 'Marta',
            dutch: 'Welkom in mijn nieuwe huis! Dit is de woonkamer.',
            spanish: '¡Bienvenida a mi nueva casa! Esta es el salón.',
          },
          {
            id: 'line-2',
            speaker: 'Lisa',
            dutch: 'Wat mooi! Is de keuken ook groot?',
            spanish: '¡Qué bonito! ¿La cocina también es grande?',
          },
          {
            id: 'line-3',
            speaker: 'Marta',
            dutch: 'Ja, de keuken is heel groot. En kijk, dit raam geeft veel licht.',
            spanish: 'Sí, la cocina es muy grande. Y mira, esta ventana da mucha luz.',
          },
          {
            id: 'line-4',
            speaker: 'Lisa',
            dutch: 'Waar is de badkamer?',
            spanish: '¿Dónde está el cuarto de baño?',
          },
          {
            id: 'line-5',
            speaker: 'Marta',
            dutch: 'De badkamer is naast de slaapkamer, aan het einde van de gang.',
            spanish: 'El cuarto de baño está al lado del dormitorio, al final del pasillo.',
          },
        ],
      },
    },
    { type: 'review' },
  ],
};

const lesson_compras: Lesson = {
  id: 'ir-de-compras',
  moduleId: 'vida-cotidiana',
  title: 'Ir de compras',
  subtitle: 'Vocabulario para comprar en el supermercado',
  order: 2,
  learningObjective: 'Comprar productos básicos y preguntar precios',
  estimatedMinutes: 20,
  blocks: [
    {
      type: 'vocabulary',
      items: [
        {
          id: 'supermarkt',
          dutch: 'supermarkt',
          spanish: 'el supermercado',
          article: 'de',
          emoji: '🏬',
          color: '#1D0084',
          exampleNl: 'Ik ga naar de supermarkt.',
          exampleEs: 'Voy al supermercado.',
          category: 'compras',
          difficulty: 'A1',
        },
        {
          id: 'brood',
          dutch: 'brood',
          spanish: 'el pan',
          article: 'het',
          emoji: '🍞',
          color: '#025dc7',
          exampleNl: 'Ik koop elke dag vers brood.',
          exampleEs: 'Compro pan fresco todos los días.',
          category: 'compras',
          difficulty: 'A1',
        },
        {
          id: 'melk',
          dutch: 'melk',
          spanish: 'la leche',
          article: 'de',
          emoji: '🥛',
          color: '#0b4db5',
          exampleNl: 'Ik drink elke ochtend melk.',
          exampleEs: 'Bebo leche todas las mañanas.',
          category: 'compras',
          difficulty: 'A1',
        },
        {
          id: 'kaas',
          dutch: 'kaas',
          spanish: 'el queso',
          article: 'de',
          emoji: '🧀',
          color: '#0a3d9e',
          exampleNl: 'Nederlandse kaas is erg lekker.',
          exampleEs: 'El queso holandés está muy rico.',
          category: 'compras',
          difficulty: 'A1',
        },
        {
          id: 'appel',
          dutch: 'appel',
          spanish: 'la manzana',
          article: 'de',
          emoji: '🍎',
          color: '#1440a0',
          exampleNl: 'Een appel per dag is gezond.',
          exampleEs: 'Una manzana al día es sano.',
          category: 'compras',
          difficulty: 'A1',
        },
        {
          id: 'water',
          dutch: 'water',
          spanish: 'el agua',
          article: 'het',
          emoji: '💧',
          color: '#0d5295',
          exampleNl: 'Ik drink veel water.',
          exampleEs: 'Bebo mucha agua.',
          category: 'compras',
          difficulty: 'A1',
        },
      ],
    },
    {
      type: 'phrases',
      items: [
        {
          id: 'phrase-hoeveel-kost',
          dutch: 'Hoeveel kost dit?',
          spanish: '¿Cuánto cuesta esto?',
          context: 'Preguntando el precio',
        },
        {
          id: 'phrase-heeft-u-ook',
          dutch: 'Heeft u ook...?',
          spanish: '¿Tienen también...?',
          context: 'Buscando un producto',
        },
        {
          id: 'phrase-ik-wil-graag',
          dutch: 'Ik wil graag een brood, alsjeblieft.',
          spanish: 'Quisiera un pan, por favor.',
          context: 'Pidiendo un producto',
        },
        {
          id: 'phrase-vijf-euro',
          dutch: 'Dat is vijf euro, alsjeblieft.',
          spanish: 'Son cinco euros, por favor.',
          context: 'Pagando',
        },
      ],
    },
    {
      type: 'practice',
      exercises: [
        {
          id: 'ex-brood-artikel-mc',
          type: 'multiple_choice',
          prompt: '¿Qué artículo lleva "brood"?',
          options: ['het', 'de', 'een', 'geen'],
          correctAnswer: 'het',
        },
        {
          id: 'ex-melk-mc',
          type: 'multiple_choice',
          prompt: '¿Cómo se dice "la leche"?',
          options: ['melk', 'brood', 'kaas', 'water'],
          correctAnswer: 'melk',
        },
        {
          id: 'ex-precio-mc',
          type: 'multiple_choice',
          prompt: '¿Qué frase usas para preguntar el precio?',
          options: ['Hoeveel kost dit?', 'Waar is de supermarkt?', 'Ik wil graag...', 'Heeft u ook...?'],
          correctAnswer: 'Hoeveel kost dit?',
        },
        {
          id: 'ex-ik-wil-order',
          type: 'order_sentence',
          prompt: 'Ordena estas palabras para formar la frase correcta',
          options: ['alsjeblieft', 'brood', 'graag', 'Ik', 'wil', 'een'],
          correctAnswer: 'Ik wil graag een brood alsjeblieft',
        },
      ],
    },
    {
      type: 'dialogue',
      dialogue: {
        id: 'dialogue-supermarkt',
        title: 'En el supermercado',
        context: 'Carlos hace la compra en un supermercado neerlandés.',
        lines: [
          {
            id: 'line-1',
            speaker: 'Carlos',
            dutch: 'Goedemiddag! Heeft u ook biologische melk?',
            spanish: '¡Buenas tardes! ¿Tienen también leche ecológica?',
          },
          {
            id: 'line-2',
            speaker: 'Medewerker',
            dutch: 'Ja hoor, die staat in het koelvak achteraan.',
            spanish: 'Sí, está en la nevera del fondo.',
          },
          {
            id: 'line-3',
            speaker: 'Carlos',
            dutch: 'En hoeveel kost het brood?',
            spanish: '¿Y cuánto cuesta el pan?',
          },
          {
            id: 'line-4',
            speaker: 'Medewerker',
            dutch: 'Het brood kost twee euro vijftig.',
            spanish: 'El pan cuesta dos euros cincuenta.',
          },
          {
            id: 'line-5',
            speaker: 'Carlos',
            dutch: 'Prima. Ik neem een brood en twee flessen water, alsjeblieft.',
            spanish: 'Perfecto. Me llevo un pan y dos botellas de agua, por favor.',
          },
        ],
      },
    },
    { type: 'review' },
  ],
};

const lesson_tiempo_libre: Lesson = {
  id: 'tiempo-libre',
  moduleId: 'vida-cotidiana',
  title: 'Tiempo libre',
  subtitle: 'Actividades de ocio y hobbies',
  order: 3,
  learningObjective: 'Hablar sobre aficiones y actividades de ocio en neerlandés',
  estimatedMinutes: 25,
  blocks: [
    {
      type: 'vocabulary',
      items: [
        {
          id: 'lezen',
          dutch: 'lezen',
          spanish: 'leer',
          article: null,
          emoji: '📚',
          color: '#1D0084',
          exampleNl: 'In mijn vrije tijd lees ik graag.',
          exampleEs: 'En mi tiempo libre me gusta leer.',
          category: 'ocio',
          difficulty: 'A1',
        },
        {
          id: 'muziek',
          dutch: 'muziek',
          spanish: 'la música',
          article: 'de',
          emoji: '🎵',
          color: '#025dc7',
          exampleNl: 'Ik hou van muziek.',
          exampleEs: 'Me encanta la música.',
          category: 'ocio',
          difficulty: 'A1',
        },
        {
          id: 'fietsen',
          dutch: 'fietsen',
          spanish: 'ir en bici',
          article: null,
          emoji: '🚲',
          color: '#0b4db5',
          exampleNl: 'We gaan dit weekend fietsen.',
          exampleEs: 'Este fin de semana salimos en bici.',
          category: 'ocio',
          difficulty: 'A1',
        },
        {
          id: 'koken',
          dutch: 'koken',
          spanish: 'cocinar',
          article: null,
          emoji: '👨‍🍳',
          color: '#0a3d9e',
          exampleNl: 'Ik kook graag voor mijn vrienden.',
          exampleEs: 'Me gusta cocinar para mis amigos.',
          category: 'ocio',
          difficulty: 'A1',
        },
        {
          id: 'vrienden',
          dutch: 'vrienden',
          spanish: 'los amigos',
          article: 'de',
          emoji: '👫',
          color: '#1440a0',
          exampleNl: 'Ik zie mijn vrienden in het weekend.',
          exampleEs: 'Veo a mis amigos el fin de semana.',
          category: 'ocio',
          difficulty: 'A1',
        },
        {
          id: 'film',
          dutch: 'film',
          spanish: 'la película',
          article: 'de',
          emoji: '🎬',
          color: '#0d5295',
          exampleNl: 'We kijken vanavond een film.',
          exampleEs: 'Esta noche vemos una película.',
          category: 'ocio',
          difficulty: 'A1',
        },
      ],
    },
    {
      type: 'phrases',
      items: [
        {
          id: 'phrase-vrije-tijd',
          dutch: 'In mijn vrije tijd...',
          spanish: 'En mi tiempo libre...',
          context: 'Hablando de hobbies',
        },
        {
          id: 'phrase-hou-van-muziek',
          dutch: 'Ik hou van muziek.',
          spanish: 'Me encanta la música.',
          context: 'Expresando gustos',
        },
        {
          id: 'phrase-wat-doe-jij',
          dutch: 'Wat doe jij graag?',
          spanish: '¿Qué te gusta hacer?',
          context: 'Preguntando por aficiones',
        },
        {
          id: 'phrase-zullen-fietsen',
          dutch: 'Zullen we samen fietsen?',
          spanish: '¿Salimos juntos en bici?',
          context: 'Haciendo planes',
        },
      ],
    },
    {
      type: 'practice',
      exercises: [
        {
          id: 'ex-lezen-mc',
          type: 'multiple_choice',
          prompt: '¿Cómo se dice "leer" en neerlandés?',
          options: ['lezen', 'koken', 'fietsen', 'muziek'],
          correctAnswer: 'lezen',
        },
        {
          id: 'ex-wat-doe-jij-mc',
          type: 'multiple_choice',
          prompt: '¿Qué frase usas para preguntar por los hobbies de alguien?',
          options: ['Wat doe jij graag?', 'Hoe gaat het?', 'Waar is de markt?', 'Ik hou van lezen.'],
          correctAnswer: 'Wat doe jij graag?',
        },
        {
          id: 'ex-film-listen',
          type: 'listen_and_choose',
          prompt: 'Escucha y elige el hobby mencionado: "In mijn vrije tijd kijk ik graag films."',
          options: ['koken', 'lezen', 'film kijken', 'fietsen'],
          correctAnswer: 'film kijken',
          explanation: 'Kijk ik graag films significa que le gusta ver películas.',
        },
        {
          id: 'ex-hou-van-muziek-write',
          type: 'write_answer',
          prompt: 'Escribe en neerlandés: "Me encanta la música."',
          correctAnswer: 'Ik hou van muziek.',
        },
      ],
    },
    {
      type: 'dialogue',
      dialogue: {
        id: 'dialogue-fds',
        title: 'Planes para el fin de semana',
        context: 'Dos amigos hablan sobre qué van a hacer el fin de semana.',
        lines: [
          {
            id: 'line-1',
            speaker: 'Sara',
            dutch: 'Hey, wat doe je dit weekend?',
            spanish: 'Oye, ¿qué haces este fin de semana?',
          },
          {
            id: 'line-2',
            speaker: 'Javier',
            dutch: 'In mijn vrije tijd lees ik graag, maar dit weekend wil ik fietsen.',
            spanish: 'En mi tiempo libre me gusta leer, pero este fin de semana quiero salir en bici.',
          },
          {
            id: 'line-3',
            speaker: 'Sara',
            dutch: 'Leuk! Ik hou ook van fietsen. Zullen we samen gaan?',
            spanish: '¡Qué bien! A mí también me encanta la bici. ¿Vamos juntos?',
          },
          {
            id: 'line-4',
            speaker: 'Javier',
            dutch: 'Ja, dat is goed! En daarna kunnen we een film kijken.',
            spanish: '¡Sí, perfecto! Y después podemos ver una película.',
          },
          {
            id: 'line-5',
            speaker: 'Sara',
            dutch: 'Top! En ik kook dan voor ons allebei.',
            spanish: '¡Genial! Y yo cocino para los dos.',
          },
        ],
      },
    },
    { type: 'review' },
  ],
};

/* ─────────────────────────────────────────────────────────────────────────────
   EXPORTS
───────────────────────────────────────────────────────────────────────────── */

export const LESSONS: Lesson[] = [
  lesson_saludos,
  lesson_numeros,
  lesson_ciudad,
  lesson_casa,
  lesson_compras,
  lesson_tiempo_libre,
];
